openapi: 3.0.0
info:
  title: Custom API
  version: v1
paths:
  /users:
    x-amf-displayName: Users
    get:
      description: Get all the users.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users.User[]"
      servers:
        -
          url: https://custom.api.com
  /users/{userId}:
    x-amf-displayName: User
    get:
      parameters:
        -
          name: userId
          required: true
          in: path
          schema:
            title: User ID
            type: integer
      requestBody:
        content: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users.User"
      servers:
        -
          url: https://custom.api.com
  /users/me:
    x-amf-displayName: Current user
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users.User"
      servers:
        -
          url: https://custom.api.com
  /users/me/advanced:
    x-amf-displayName: Current advanced user
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users.AdvancedUser"
      servers:
        -
          url: https://custom.api.com
  /customers:
    x-amf-displayName: Customers
    get:
      description: Get all the customers.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customers.Customer[]"
      servers:
        -
          url: https://custom.api.com
components:
  schemas:
    users.User[]:
      title: Users
      description: A user collection
      type: array
      items:
        title: User
        description: A simple user
        type: object
        additionalProperties: true
        required:
          - name
        properties:
          id:
            description: User ID
            type: integer
          name:
            description: User name
            type: string
    users.User:
      title: User
      description: A simple user
      type: object
      additionalProperties: true
      required:
        - name
      properties:
        id:
          description: User ID
          type: integer
        name:
          description: User name
          type: string
    users.AdvancedUser:
      title: AdvancedUser
      description: An advanced user
      type: object
      additionalProperties: true
      required:
        - name
      properties:
        id:
          description: User ID
          type: integer
        name:
          description: User name
          type: string
        bestFriend:
          $ref: "#/components/schemas/users.AdvancedUser"
    customers.Customer[]:
      description: A customer collection
      type: array
      items:
        title: Customer
        description: A simple customer
        type: object
        additionalProperties: true
        required:
          - name
        properties:
          id:
            description: Customer ID
            type: integer
          company:
            description: Customer's company
            type: string
          user:
            $ref: "#/components/schemas/user"
          name: {}
    user:
      title: User
      description: A simple user
      type: object
      additionalProperties: true
      required:
        - name
      properties:
        id:
          description: User ID
          type: integer
        name:
          description: User name
          type: string
